### ISSUE TITLE
HC10のモデルの色がおかしい

### ISSUE THREAD

**Issue by Ry0** [ntl-ros-pkg/motoman_robot#16]
Gazeboで表示させたときのモデルの色がおかしいので修正する。

Blenderで２つのColladaを合体させたモデルと，そうでないモデルで白色の明るさがぜんぜん異なる

**Comment by RyodoTanaka** [comment]
輝度の設定が違ってるだけやと思う

**Comment by Ry0** [comment]
@RyodoTanaka 
テキストエディタでみればどうにかなるかな？

**Comment by Ry0** [comment]
下記のパラメータに関して色が違うパーツ間で差分があったので修正しました。
色の違いが治ったのでマージします。

```diff     
-            <ambient>
-              <color sid="ambient">0 0 0 1</color>
-            </ambient>
            <diffuse>
              <texture texture="link_b_2_png-sampler"/>
              <texture texture="link_b_2_png-sampler"/>
            </diffuse>
            <specular>
-              <color sid="specular">0.25 0.25 0.25 1</color>
+              <color sid="specular">0 0 0 1</color>
```

![Screenshot from 2019-05-13 22-20-58](https://user-images.githubusercontent.com/8924325/57624818-aea05780-75cd-11e9-924c-d1e886f2d927.png)

**Comment by RyodoTanaka** [comment]
なるほど
勉強になりました
ありがとう！
