### ISSUE TITLE
motominiのイナーシャを設定したい

### ISSUE THREAD

**Issue by MoriKen254** [ntl-ros-pkg/motoman_robot#3]
今マスワークスのすごい技術者とタッグを組んで、MATLAB経由で、motominiをgazebo上でぶん回して社外講演会でプレゼンしようと画策しています。面白そうじゃありませんか？

https://github.com/ntl-ros-pkg/motoman_robot/tree/mk/add-motomini でmotominiを増やしています。

とりあえず`roslaunch motoman_description motomini.launch`でそれっぽいのが出てきます。ぼちぼちGazebo対応しようというところで、ROS-Iのリポジトリだと動力学パラメータ定義されてないのかーと肩を落としています。

sia5とかだとイナーシャをシリンダ＋ボックスで近似しているように見えますが、motominiでもやりたいなーと思っています。

sia5の時はどんな風にやりましたか？
　※私はCAD苦手なので、さくさくっとできるなら協力してもらえないかな、とか。。。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
とても面白そうですね！

さて
sia5とかだとイナーシャをシリンダ＋ボックスで近似しているように見えますが、motominiでもやりたいなーと思っています。

上記についてですが
SIA5のイナーシャ情報は
シリンダとボックスで近似して
自分で手書きでもとめました…
また、その際の各パーツの質量も適当です(総質量はカタログに合わせてあります)

なので、サクッとできる訳では無いです…
ご期待に添えず、すみません。
よろしくお願いします。

**Comment by MoriKen254** [comment]
ありがとう！事情はよくわかりました。

大変そうなのがわかったので、何か適当に入れておけば良さげなパラメータとかあれば教えてもらえますか？例えば、初めて西田研にsia5がやってきたときに、とりあえずこんな感じで入れればGazebo上では問題なく動いた、レベルの簡易なものでOKです。

宜しくおねがいします。

**Comment by MoriKen254** [comment]
とりあえず以下のようにすれば、最低限行けるだろうと思ったので、進めてみますね。分からなくなったらまたつぶやきます笑。

- stlの概形から、全部リンクをシリンダと仮定してイナーシャテンソルを設定
- リンク質量は、総重量をベースに各リンクの体積比から算出

**Comment by RyodoTanaka** [comment]
@MoriKen254 
遅くなってすみません！
SIA5の時は
質量は適当(ただの勘で、体積比などは考慮してない)
各パーツの形状近似は
base_linkだけ箱
残りはシリンダと箱の組み合わせ
で作りました
ただ、組み合わせで作ると
重心位置の計算や慣性モーメントの組み合わせ計算(名前失念しましたすみません)がとても面倒
なので、
組み合わせではなく、単一の箱かシリンダで近似すれば良いと思います。
実際、最近マージしたSIA20は、箱で近似(バウンディングボックス)してます。
以上、よろしくお願いします。

**Comment by RyodoTanaka** [comment]
また、SIA20の近似した箱の重心位置も、箱の中央に設定してます。
この、重心位置に関しては臨機応変に変更しても良いかと思います。
本リポジトリでこれまでにマージしたモデルでは、ダイナミクスを考慮せねばならないほどの使用用途を考えていなかったので、動けば良いや位のかなり適当な設定です。
それから、重心位置をどこに設定するにしても、各linkの各原点位置からズレてるはずなので、urdfのinertialタグの中にoriginタグを設けて、各linkの各原点からの位置を指定してます。

**Comment by MoriKen254** [comment]
@RyodoTanaka くん

ありがとう。
とりあえず最低限gazeboで動かしたくて、原点位置の微調整等までやるのが辛いので、取り急ぎmassとbox近似したイナーシャを設定してみました。

- 変更を加えたブランチ
  - https://github.com/ntl-ros-pkg/motoman_robot/tree/mk/add-motomini
  - https://github.com/ntl-ros-pkg/motoman_simulator/tree/mk/add-motomini

そして下記コマンドでGazeboで起動するところまでやったのですが、ブルブル振動します。

```bash
roslaunch motoman_gazebo motomini_empty_world.launch
```

明らかに何か間違っているんだと思うのですが、どこを修正するべきなのか、ぱっとわからず、助けていただきたく汗。

すみませんが、知恵を貸していただけませんか。おねがいします。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
遅くなってすみません．

原因と解決策をお答えします．

# 原因
原因は2つあります．
### 1. base_link に設定しているlinkが地面にめり込んでいる
### 2. link_1とlink_2が干渉している
これは，地面との干渉ではなく，Self-Collisionが起きてる状態です．

# 解決策
### 1. base_linkがめり込んでる問題
`motomini.xacro`で設定している，`world`->`base_link`の値を，`base_link`が地面に干渉しない程度に設定する．
試しに，下の例のように，`z=0.1`に設定した所，この原因の振動はなくなりました．（適当に設定した値なので，空中に浮きます．）
正確なCAD情報を知らないので，ここの調整はおねがいします．
```xml
 <xacro:add_world>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </xacro:add_world>
```

### Self-Collision問題
これの解決法は2つあります．
##### 解決策1
`<gazebo>`タグ内で設定している，`<selfCollide>`タグの値を`false`にする．
具体的には，`motoman_description/urdf/motomini/body.gazebo.xacro`を下記のように設定すればOKです．
```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="gazebo_link_v1" params="name">
    <gazebo reference="${name}">
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
      <selfCollide>false</selfCollide>
      <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>
</robot>
```
ただ，この方法だと自己干渉はシミュレートできないです．
`motomini`単体では自己干渉しないと思うので，この設定でも大丈夫だと思います．
なお，環境とロボットはきちんと衝突がシミュレートされます．

##### 解決策2
link_1 と link_2が干渉しないようなCollisiomモデルを設定する．

以上です．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
すぐ設定出来る内容だったので，

- https://github.com/ntl-ros-pkg/motoman_robot/tree/ryodo/fix-collision
- 1393414d87293e97104e00fd4c8770a93c8bc060

にPushしました．
また，#4 にPRを出しました．

採用した解決策は以下のとおりです．

- zのoffset値は試してみて，よさ気な値を入れてあります．
- self-collision を false にして対処してます．

以上，よろしくお願いします．

**Comment by MoriKen254** [comment]
おー！もうブルブルしない！

素晴らしい！本当ありがとう！
とても勉強になりました。プルリク、即マージします。

そして、ひとまず簡易的にイナーシャも設定できたので、とりあえず良しとしてissue閉じますね。
